### ISSUE TITLE
Polyline bugs - strange behaviour at extreme join angles, freezes on `1` point

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#185]
While implementing a NOC that requires a line I noticed some issues with Polyline.
1. There's no warning for if you build a Polyline with a single vertex. It just freezes. This would seem like an avoidable mistake but if you are building with loops it's easy enough to make.
I'd like to put a panic! on < 2 vertices with a help message if that's ok with everyone?
2. There seems to be big "bleeds" where it looks like it's trying to fill a sharp angle. I might be trying to use this wrong? My goal is a series of vertices linked together by a line
![image](https://user-images.githubusercontent.com/7286454/43234834-c80a1f2c-90c1-11e8-87d8-d670d9388590.png)
```Rust
    let thickness = 1.0;
    if history.len() > 1 {
        let vertices = history.iter().map(|v| {
            geom::vertex::Rgba(pt2(v.x, v.y), Rgba::new(0.0, 0.0, 0.0, 1.0))
        }); 
    draw.polyline().vertices(thickness, vertices);
```

**Comment by mitchmindtree** [comment]
**Re 2:** Yeah you're totally right, thanks for posting this, I should have opened an issue about this when I submitted the polyline PR!

The `miter` polyline doesn't yet account for the case where an angle is super extreme - there's a bunch of writing on this but I just haven't got around to implementing it yet. Here's [one fairly thorough link describing the case and implementation](https://www.codeproject.com/articles/226569/drawing-polylines-by-tessellation) (though I'm trying to implement it as an iterator for flexibility rather than operating on whole lists at once). This is at the top of my nannou todo-list after #170 and before #167.

**Re 1:** I'm torn between whether we should `panic!` or just silently not draw any lines? The latter might be friendlier to sketchers who maybe have some sort of interactive/loop based polyline where they don't want to add this special case check for `1` point? Then again maybe `panic!`ing would be more useful for folks wondering why they can't see their polyline when they've accidentally passed less than two points. Maybe we could add a `debug_assert!` so that it `panic!`s in debug mode but "just works" in release?
