### ISSUE TITLE
Doesn't work on Windows 7 in VirtualBox

### ISSUE THREAD

**Issue by mark-summerfield** [nannou-org/nannou#190]
I'm running Windows 7-64 inside VirtualBox.

I did a git clone using "git clone https://github.com/nannou-org/nannou.git" on Linux into a folder shared by Windows. (Note that on this page: https://github.com/nannou-org/nannou the Nannou Examples section says to use "git clone https://github.com/nannou-org/nannou" which when I tried it asked for a username and password.)

Here's the error message I got:
```
OpenGL Warning: WGL_SAMPLE_BUFFERS_EXT & WGL_SAMPLES_EXT not supporteed!
thread 'main' panicked at 'could not build default app window: GlutinCreationError(NoAvailablePixelFormat)'
, libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\release\examples\simple_draw.exe` (exit code: 101)
```

The same example works perfectly on Linux though.

**Comment by mitchmindtree** [comment]
Thanks for the issue!

I could be wrong, but I believe the problem here is VirtualBox's very poor support for OpenGL on Windows. I've tried many times in the past to get OpenGL to work in my windows VirtualBox instance, but from my understanding support for OpenGL has always been very flakey and not well maintained. 

That said, there seem to be some people who have managed to have some success by installing guest additions and enabling certain settings (a quick google of VirtualBox Windows OpenGL should give lots of results), however none of these have worked for me in the past. Sorry I don't have better news, please let me know if you manage to get this working as it's something I've desired for a long time!

I'm going to close this for now as, even if we want to track progress on this issue, it would probably be better off done upstream at the [glium crate](https://github.com/glium/glium) (the OpenGL crate we currently use under the hood). If you can get the glium examples working, then nannou should also work.
