### ISSUE TITLE
The screen is blank whenever I run an example on Mac OS Mojave.

### ISSUE THREAD

**Issue by yeswecan** [nannou-org/nannou#197]
Hello there!

I've tried running nannou's examples and so far the screen is just blank in each of them. Not sure what to look for, there's nothing on console or anywhere else. Is there anything I should check to find the cause of this?

Thanks a lot for your effort!

edit: it looks a lot like this issue - https://github.com/tomaka/glutin/issues/969
But it seems fixed a while ago. Is it that nannou somehow pulled the old glutin?

**Comment by JoshuaBatty** [comment]
Hi @yeswecan thanks for pointing this out to us. We don't have a Mojave OS to test on so thanks for pointing it out. We will take a look at the glutin issue and work to get this working. I'll ping you on here when we think a fix has been made so you can test again for us if that's ok. Cheers.

**Comment by yeswecan** [comment]
Hey @JoshuaBatty!

I can look into it myself if you can point me in the right direction if that works for you. I'm not at all familiar with Rust but I could probably try a few things and see if that works and/or test something out on Mojave (if that's even a Mojave thing, I also have a High Sierra hackintosh which I could compare against locally). Let me know if you want me to try smth.

**Comment by MacTuitui** [comment]
If someone else is facing the same issue, I was not able to use the replace feature of cargo to do the thing it's supposed to do (maybe because the version was not bumped or more probably just because I'm a complete beginner), so I had to add a local override in ~/.cargo/config by specifying the path to winit directly:

`paths = ['path/to/git/clone/of/winit']`

Now the nannou examples work but I have a ugly warning that this feature is not meant to be used that way.
