### ISSUE TITLE
MacOs doesn't open in fullscreen

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#306]
If you call
```rust
    let window_id = app
        .new_window()
        .with_fullscreen(true)
        .view(view)
        .build()
        .unwrap();
```
It just opens up maximized.
I'm not sure if this happens on other OS.

**Comment by mitchmindtree** [comment]
It fullscreens correctly on X11 Linux I believe.

Does it fullscreen properly on macos when you use Cmd+F? That calls `set_fullscreen` under the hood if the window is already created.

I'd imagine there would be an issue for this in winit as we pretty much just call the winit methods directly under the hood.

**Comment by freesig** [comment]
Yep you can get to fullscreen with `Cmd+F`. I'll have a dig into this when I get a chance. It crashes though due to the segfault bug.

**Comment by freesig** [comment]
```rust
let mon = app.main_window().current_monitor();
app.main_window().set_fullscreen(Some(mon));
```
This works actually. I think maybe it just needs the `MonitorId`

**Comment by vl4dimir** [comment]
@freesig is there a way to start the app in fullscreen immediately? This is sort of a chicken and egg problem, you need the `MonitorId` to create a window with `with_fullscreen` (not `set_fullscreen` after the fact), but the only way I've found to get `MonitorId` is if I already have a window. 😆

This wouldn't be that important if window resizing worked on macOS, but it is currently unusable due to https://github.com/nannou-org/nannou/issues/372. So at the moment, no fullscreen windows on macOS.
