### ISSUE TITLE
Colors in docs are not completely implemented

### ISSUE THREAD

**Issue by SjorsVanGelderen** [nannou-org/nannou#345]
The docs mention a host of colors that are not actually available in the `nannou::color::named` namespace.
For instance, `nannou::color::named::ALICEBLUE` does not actually exist.
Should these still be implemented, or should the tango colours that exist in the source now not be expanded upon?

**Comment by mitchmindtree** [comment]
Thanks for the issue!

I think the first course of action should be to update to the latest version of the `palette` crate (the crate used for nannou's color module). I tried updating to version 0.3 when it came out a little while back, but there were some issues with the API that made it very difficult and I never got around to finishing it. I believe the latest version, 0.4, should make this quite a bit easier to do. Once we've updated palette maybe then we can look at making those named colors easier to access and use with nannou?

**Comment by SjorsVanGelderen** [comment]
The `palette` crate has some changes in the data structures and traits that break compatibility with the `nannou` codebase.
I've tried to resolve these issues, but with little luck so far.
For instance, I'm not sure how to resolve the missing field `standard` in the `make_color!` macro.
It's supposed to contain `PhantomData`.
My experience with macros and traits is probably too limited to fix this by myself.

Also, how configurable by `nannou` users should this really be?
Do we really need to allow users to set the `RgbStandard` as well as the component type (`f32`)?
Maybe it's not so relevant at this time.

I'd be interested to hear your thoughts.

**Comment by mitchmindtree** [comment]
Thanks a lot for the update @SjorsVanGelderen!

> Also, how configurable by nannou users should this really be?
> Do we really need to allow users to set the RgbStandard as well as the component type (f32)?
> Maybe it's not so relevant at this time.

This is a really good point. While `palette` is nice and thorough for properly understanding what's going on with conversions and different formats, all of the info that it exposes is probably a little overkill for our needs. I'd like to have another stab at updating `palette` myself and see if I can make a slightly higher-level abstraction on top with some reasonable defaults so that users don't have to worry about things like `RgbStandard` if they don't want to. Quite a few users have been running into issues w.r.t colors lately (totally understandably!) so I'm going to bump this up my list and try have a go at it tonight.
