### ISSUE TITLE
Colors seem dark in 0.10

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#370]
I'm not sure if this is a bug or if the new color words are just darker.
It's been confirmed on Mac OS and Arch.
Looks like this for `simple_draw`:
![image](https://user-images.githubusercontent.com/7286454/61681210-eb1bcc80-ad4f-11e9-8a3a-c9df481abd58.png)

**Comment by mitchmindtree** [comment]
A difference in colours is expected between 0.9 and 0.10 as we use a new set of named colours - the new ones are just rough approximations of the original colours.

That said, if there is a difference between what two people are seeing on the same version of nannou (0.10) then there is a problem that hasn't yet been solved by #355 or a new one introduced.

Here is @MacTuitui's screenshot for easier reference:

![simple_draw](https://user-images.githubusercontent.com/4587373/61706273-efdc8280-ad47-11e9-9750-924bed3cf698.png)

There's definitely a clear difference between the two images - @MacTuitui's is the expected image.

@freesig can you share a screenshot of `cargo run --example named_color_reference` with the "BROWN" colour selected? It will be much more useful for me to check what's going on.

Here's the expected output and the result I get on my machine:

![Screenshot from 2019-07-23 12-50-55](https://user-images.githubusercontent.com/4587373/61706524-92950100-ad48-11e9-8feb-3dc4e504c26d.png)

Here's a [link to the CSS reference](https://www.w3schools.com/cssref/css_colors.asp) where you can check the colours against the spec.

I tested the changes in #355 on both my laptop and @JoshuaBatty  and both were working nicely, but not since switching from a render pass to using the blit image command to do the final linear -> non-linear conversion as mentioned [here](https://github.com/nannou-org/nannou/pull/355#issuecomment-513549583). It could be that the moltenvk driver doesn't properly implement this and I'll have to switch it back to use a renderpass. I'll try and do another test on @JoshuaBatty's mac today next time it's free.

**Comment by mitchmindtree** [comment]
I just tested 0.10 master on @JoshuaBatty's MBP and it seems to be behaving correctly (matches the CSS spec and what myself and mactuitui are getting). Hopefully a screenshot of `examples/named_color_reference.rs` will give a better idea of what's going on with your colours @freesig.

**Comment by freesig** [comment]
Thanks for the detailed reply. You're probably right, it's probably just the names point to different colours now.
Here is that example on my machine with the css brown by it's side:
![image](https://user-images.githubusercontent.com/7286454/61753693-9af64600-adf3-11e9-93c8-7b622e285e9b.png)
I think there's a slight difference but maybe that's just firefox rendering it slightly different then vulkan?
To me MacTuiTui's looks the same as mine but I honestly don't think I have the most sensitive eyes to this sort of thing.
I'm happy to close this issue but reopen if you think something is off.
