### ISSUE TITLE
Exiting the application.

### ISSUE THREAD

**Issue by BorisKourt** [nannou-org/nannou#377]
I am trying to find a way to trigger a graceful exit from within nannou (something that runs the specified exit function before quitting for example) 

Is there a way to implement this right now?

**Comment by mitchmindtree** [comment]
@BorisKourt thanks for the issue!

Embarrassingly, I don't think there is!

What kind of API would you like to see to allow for this? I'm thinking perhaps a simple `app.exit()` method which can be called from anywhere (e.g. in `model`, `update`, `key_pressed`, etc) so that, once the current function returns, nannou will automatically stop looping, call the user's `exit` function if there is one, and then return?

**Comment by BorisKourt** [comment]
I think that would be the best option. All other logic can be ether in exit or before `app.exit()` gets called.
