### ISSUE TITLE
Add in an event to retrieve keyboard events as a string

### ISSUE THREAD

**Issue by JoshuaBatty** [nannou-org/nannou#480]
Currently there is no way to easily get key pressed events as a String. Conrod has this feature for example.

**Comment by mitchmindtree** [comment]
To do this I think we want to:

- Add a `WindowEvent::Text(char)` variant
- Check for this event https://docs.rs/winit/0.22.0/winit/event/enum.DeviceEvent.html#variant.Text
- Check the currently focused `WindowId` and deliver the `char` via the new `WindowEvent::Text` variant.
- Add a `TextFn` and a `text` method to the `WindowBuilder` that allows providing a function for handling text events so that users don't have to match on `WindowEvent`.
- Add a `Event::Text` that gets called for every winit `DeviceEvent::Text` that occurs regardless of window focus.
- Add an app `text` builder method for the above.

It would be worth having a look at how conrod does this too - I think there is a specific set of `char`s that it filters out/ignores that are generated by the modifier keys on some systems that you never want to handle in a practical sense.

**Comment by gmunk** [comment]
Hello,

I've forked the repository and done some work on this issue, I want to open a PR but first I'd like to ask two questions:
1. Is this something that is still desirable, seeing the issue was opened more than an year ago?
2. At the moment there is an error when running the script which checks whether the examples have had any regressions, I've seen that this same error is present in, at least, one of the most recent three actions runs on the repo. So should I wait for this error to be resolved or should I open my PR?

PS: The error in my second question is the following:
`error[E0599]: no function or associated item named `new_immediate` found for struct `FsEventWatcher` in the current scope
   --> /Users/r3xus/.cargo/git/checkouts/hotglsl-4b7ab76e967c6433/0066dea/src/lib.rs:174:51
    |
174 |     let mut watcher = notify::RecommendedWatcher::new_immediate(move |res| {
    |                                                   ^^^^^^^^^^^^^ function or associated item not found in `FsEventWatcher`
`

**Comment by mitchmindtree** [comment]
Hi @gmunk!

1. Yes, I think this is still something that would be nice to have - currently I think it's only accessible by accessing the "raw" winit events, but it would be nice to have a more easily accessible event.

2. Yes this appeared in the last couple of days - it looks like there may have been some breakage in the public API for the `notify` crate upstream. I plan to look into investigate this morning to see what's going on. It doesn't affect the majority of nannou (only the hotloading example), but it's breaking CI so I'd like to clean it up.

**Comment by JoshuaBatty** [comment]
I ran into this issue this morning and got around it by upgrading the notify dependency version. I have a PR open [here](https://github.com/nannou-org/hotglsl/pull/1) if you want to take a look mitchie.
