### ISSUE TITLE
Quick question: how would I go about moving the camera of the view?

### ISSUE THREAD

**Issue by stefanlenoach** [nannou-org/nannou#542]
For example lets say just wanted to move the camera continuously away from a circle drawn in the center of my window, how would I do something like that? Didn't see any mention of this sort of behavior in the docs. Thank you!

**Comment by mitchmindtree** [comment]
Thanks for the issue @stefanlenoach !

Unfortunately we don't yet have a convenient `draw.camera(&my_cam)` method or anything like this just yet, but it is something that has been on my mind and would likely be very easy to add! Under the hood, the `Draw` API renderer uses a perspective matrix to efficiently transform all points in the vertex shader. Currently we only use this to map points to the range expected by the fragment shader, though we could use this same matrix to allow for camera-like perspectives into the scene, rather than just the orthographic 2D style perspective we currently have.

In the meantime, you can kind of create this distancing movement effect by using the `draw` transformation methods like `draw.z(z)`, `draw.scale(s)`, etc. The `draw_transform.rs` example might give a good idea of how to go about this.

Otherwise the very verbose way would be to setup your own pipeline, similar to the `wgpu_teapot_camera.rs` example. This is a lot more powerful than the `Draw` API, but also quite a bit trickier if you're new to low-level graphics. Hopefully we can provide some more resources for this sort of stuff in the future, for now [this guide](https://sotrh.github.io/learn-wgpu/#what-is-wgpu) is a great read if you're interested in better understanding wgpu (nannou's graphics backend).

I hope this helps!

**Comment by stefanlenoach** [comment]
Thanks @mitchmindtree, your comment was very helpful!
