### ISSUE TITLE
Hsl representations do not match reference implementations

### ISSUE THREAD

**Issue by ericyd** [nannou-org/nannou#589]
**Summary**

The rendering of HSL colors differs sometimes quite significantly from reference implementations.

I'm not clear on where upstream dependencies end, and nannou begins, so this issue may belong in another repo. Please feel free to point me in the right direction if this is an upstream issue.

---

**How to reproduce**

I'm pretty basic, so my "reference implementations" are web based color pickers
* https://www.google.com/search?q=colorpicker
* http://www.workwithcolor.com/hsl-color-picker-01.htm

If you generate a color in nannou using the values from these color pickers, comparing the output of Hsl and Rgb structs is quite different even though they match in the color picker sites.

```rust
extern crate nannou;

use nannou::prelude::*;
use nannou::color::*;

fn main() {
  nannou::sketch(view).run()
}

// http://www.workwithcolor.com/hsl-color-picker-01.htm
// https://www.google.com/search?q=colorpicker

fn view(app: &App, frame: Frame) {
  app.set_loop_mode(LoopMode::loop_ntimes(1));
  let draw = app.draw();
  draw.background().color(WHITE);

  // hsl1 and rgb should be equivalent based on reference implementations
  let hsl1 = Hsl::new(RgbHue::from_degrees(224.0), 0.88, 0.35);
  let rgb = rgb(11. / 255., 53. / 255., 168. / 255.);
  let hsl2 = Hsl::from(rgb);

  // hsl1 and hsl2 components do not match
  let (h1, s1, l1) = hsl1.into_components();
  let h1 = h1.to_positive_degrees() / 360.0;
  let (h2, s2, l2) = hsl2.into_components();
  let h2 = h2.to_positive_degrees() / 360.0;
  println!("
  h1 {} -- h2 {}
  s1 {} -- s2 {}
  l1 {} -- l2 {}
  ", h1, h2, s1, s2, l1, l2);

  // the colors are distinctly different
  draw.rect().x(-200.0).w_h(100.0, 100.0).color(hsl1);
  draw.rect().x(0.0).w_h(100.0, 100.0).color(rgb);
  draw.rect().x(200.0).w_h(100.0, 100.0).color(hsl2);

  draw.to_frame(app, &frame).unwrap();
}
```

Output of print statement:

```
  h1 0.62222224 -- h2 0.65281963
  s1 0.88 -- s2 0.9830521
  l1 0.35 -- l2 0.19745955
```

Screenshot of the colors

<img width="601" alt="Screen Shot 2020-05-03 at 6 35 35 PM" src="https://user-images.githubusercontent.com/8379268/80931241-5083fb80-8d6d-11ea-998c-88ca7f9b0b81.png">

**Comment by MacTuitui** [comment]
What you experience here is the difference between _linear_ color spaces and what is actually used for rendering. This might be the best I've found so far that explains what is happening: https://stackoverflow.com/a/12894053/1095028

So if you want to do correct color manipulation, you should be using _linear_ color spaces, yet because of the legacy behind _sRGB_ and others, you have a lot of things that are still happening in _sRGB_ and derivatives.

The issue here is that the crate that nannou uses for color (palette) is using _linear_ HSL and not the one based on _sRGB_. So the values you use to create `hsl1` should be linear, but they are not. Note that nannou will perform the conversion for you when you define a color from RGB (as in _sRGB_).

It's going to be fixed in the next release of `palette` though: https://github.com/Ogeon/palette/issues/187

**Comment by ericyd** [comment]
Thanks! I was suspecting that it might be related to `palette` but I wasn't sure where to start looking. I appreciate the issue reference and the SO post.

Indeed, as noted in the `palette` issue, if I change the rgb conversion from
```
let rgb = rgb(11. / 255., 53. / 255., 168. / 255.);
```
to
```
let rgb = LinSrgb::new(11. / 255., 53. / 255., 168. / 255.);
```
Then the results are consistent and the image outputs are all the same.

I'll close this -- thanks again!
