### ISSUE TITLE
I think the Slack inviter is broken, I simply cannot join the Slack server, I haven't received the invite

### ISSUE THREAD

**Issue by cata0309** [nannou-org/nannou#640]

**Comment by mitchmindtree** [comment]
Sorry about that @cata0309! We only have the free version of slack and so are required to manually accept all the invites (cc @JoshuaBatty ).

In the meantime you can join the chat immediately via [our matrix community rooms](https://matrix.to/#/+nannou:matrix.org). There's a bridged room for every channel in the slack, so that both are part of the same discussion. We personally use the Element Matrix client.

**Comment by cata0309** [comment]
Matrix is awesome ! Thanks
