### ISSUE TITLE
How do I declare variables that last in both view and update?

### ISSUE THREAD

**Issue by Joe23232** [nannou-org/nannou#680]
https://www.guide.nannou.cc/tutorials/basics/sketch-vs-app.html#apps

So according to this code:

```rust
use nannou::prelude::*;

fn main() {
    nannou::app(model).update(update).run();
}

struct Model {
    _window: window::Id,
}

fn model(app: &App) -> Model {
    let _window = app.new_window().view(view).build().unwrap();
    Model { _window }
}

fn update(_app: &App, _model: &mut Model, _update: Update) {}

fn view(app: &App, _model: &Model, frame: Frame) {
    let draw = app.draw();
    draw.background().color(PLUM);
    draw.ellipse().color(STEELBLUE);
    draw.to_frame(app, &frame).unwrap();
}
```

Lets just say I have a `struct` and an `impl` for a shape. If I were to call initialisation inside the `view()` function, how would I run it inside the update function? E.g.

```rust
fn view(app: &App, _model: &Model, frame: Frame) {
    let draw = app.draw();
    let square = shape::Square::init(); // this has predefined colors, positions and size. The size will be updating
    draw.to_frame(app, &frame).unwrap();
}
```

**Comment by MacTuitui** [comment]
That what `Model` is for. The model is where you place all your data. You would have something like:

```
struct Model {
   square:Square,
}

fn model(app: &App) -> Model {
   //That's where you would create all your data
   let square = shape::Square::init();
   Model{
      square,
   }
}
```

Then notice that you have a `&mut Model` in `update`: that's where you can mutate your data. You can't do that in `view`, because it's only a reference, not a mutable one. This is a design choice from nannou where you can't mutate things when you are drawing them. Coming from processing it might be hard to adapt to this choice, but it makes things clearer.

**Comment by Joe23232** [comment]
I see, thanks mate :)
