### ISSUE TITLE
Suggestion to simplify it as much as python's imitation of processing

### ISSUE THREAD

**Issue by Joe23232** [nannou-org/nannou#681]
I wanted to suggest to simplify the code to something similar like Python's Processing API

```python
def setup():
    size(480, 120)

def draw():
    if  mousePressed:
        fill(0)
    else:
        fill(255)
    ellipse(mouseX, mouseY, 80, 80)
```

[Source](https://py.processing.org/tutorials/gettingstarted/)

Wouldn't it be possible if nannou looked something like this:

```rust
use nannou::prelude::*;

fn setup()
{
	size(480, 120);
}
fn draw()
{
	if mouse_pressed
	{
		fill(0);
	}
	else
	{
		file(255);
	}
	ellipse(mouseX, mouseY, 80, 80);
}
```

Rather than something like this:

```rust
use nannou::prelude::*;

fn main() {
    nannou::app(model).update(update).run();
}

struct Model {
    _window: window::Id,
}

fn model(app: &App) -> Model {
    let _window = app.new_window().view(view).build().unwrap();
    Model { _window }
}

fn update(_app: &App, _model: &mut Model, _update: Update) {}

fn view(app: &App, _model: &Model, frame: Frame) {
    let draw = app.draw();
    draw.background().color(PLUM);
    draw.ellipse().color(STEELBLUE);
    draw.to_frame(app, &frame).unwrap();
}
```

I think this will be easier as the user does not have to see code that is unknown to them as to how it works, for example `let _window = app.new_window().view(view).build().unwrap();`.

I think this makes the code more simple and easier to work with, especially for new comers.

(I understand I made a somewhat similar post in regards with `macroquad` but I think this would really make it look a lot better if it is made to be as simple as Python processing API).

**Comment by MacTuitui** [comment]
Hi again!

As for your example, I'll tell you the same as I said in the other post (also, if the answer is good for you, please "close" the issues): you are not using the "simplest" form of what nannou can work with. The part that you find hard to understand is not needed, so... it's there to guide you through the process you seem to be going through right now: find out how the framework is designed, and what are its strengths and weaknesses. Things in Rust need to be more clearly stated, otherwise things will break, and hard, but the compiler will prevent you from doing a lot of bad things. Again, how would you deal with data in your example: who owns that data? What functions call mutate that data? 

I guess it all comes to design choices eventually. You are asking a very good question here: "the user does not have to see code that is unknown to them as to how it works". Do you want something that is "simple" because everything is hidden, or do you want something that is "flexible" because eventually you can get into the inner parts, at the cost of a few extra steps (and let's be honest here, it's just two lines)? 

Personally (not being a part of nannou's team, just one heavy user's opinion) I find the latter more attractive. I was able to do crazy shader stuff with 3D data because nannou let me access its internal `frame` (the one you need to `draw.to_frame()`). Good luck trying to do something outside what processing (especially the python one) is offering you.

So the rude answer would be to say that if what processing is offering you in terms of api is more appealing to you, please use that. The more productive answer was that nannou was not meant (imho) to be a "processing in rust", so there will be trade-offs that at first I did not understand (because of design choices for some of them, but mostly because I was - and still am - not very good at Rust). Now that I've spent almost two years working daily with the framework, I get it. I'm still pushing for having a `&mut Model` in `view()` for days where I'm super lazy, but I completely understand why the team decided to split `update()` and `view()`. 

Also join the chat, it might be easier to discuss topics like this!

**Comment by Joe23232** [comment]
> Hi again!

Hey man :)

> also, if the answer is good for you, please "close" the issues

Sure done mate.

> Do you want something that is "simple" because everything is hidden, or do you want something that is "flexible" because eventually you can get into the inner parts, at the cost of a few extra steps (and let's be honest here, it's just two lines)?

Ah I see, now I get it mate.

> So the rude answer would be to say that if what processing is offering you in terms of api is more appealing to you, please use that.

I actually have, but there was a huge bottleneck and the performance is awful that it ends up lagging up the system. I have even made some simple program which moves a circle around and there was far more resources taken up compared to Rust `macroquad` (I haven't tried this in `nannou` but I am sure it will be similar).

> The more productive answer was that nannou was not meant (imho) to be a "processing in rust", so there will be trade-offs that at first I did not understand (because of design choices for some of them, but mostly because I was - and still am - not very good at Rust). Now that I've spent almost two years working daily with the framework, I get it.

Ah I see, I will dive more into `nannou` then and I will try and learn its API.

> I'm still pushing for having a &mut Model in view() for days where I'm super lazy,

By the way how come it is not mutable inside `view()` just curious to know?

> Also join the chat, it might be easier to discuss topics like this!

Where is the chat for this?

**Comment by MacTuitui** [comment]
You're getting into the meat of the problem. Everything is a trade-off, so to get the performance of nannou (that depends on webgpu, something that is *not* by any standard a stable thing, but awesome nonetheless), you'll have to accept that things might break, but also that people are working on those same things to make them the best possible. Those inner workings have needs that might be obvious when you know about them, but for a newcomer it's as you say confusing at best. One thing that nannou could improve is indeed the guide, and it's a huge task. 

Now on the `&mut Model` not in `view`, that's very much a design decision, based on the Model/View/Controller pattern. You have only one way to mutate your model, and that's in `update`, and you only have one way to show things on the screen, that's on `view`. It was chosen to make things clearer and separate. (Now, this being Rust, you actually can work around this if you know what you are doing and getting mutable references anyway, but in that case, you would be pretty much proficient enough to know if what you do is actually worth doing). I'm used now to separate the "logic" from the "display" and while for some rare cases where I want to update things and show that particular change at the same time I waste some resources, it eventually makes for clearer apps.

You can join the chat via [Slack](https://communityinviter.com/apps/nannou/nannou-slack) or [Matrix](https://matrix.to/#/+nannou:matrix.org)! Feel free to ask there, if I'm awake I'll gladly help you around.

**Comment by Joe23232** [comment]
Thanks mate, I am joining in now.

**Comment by anselanza** [comment]
Close the issue?
