### ISSUE TITLE
Clear with opacity does not work

### ISSUE THREAD

**Issue by cdecompilador** [nannou-org/nannou#848]
Just that, neither 
```rust
let draw = app.draw();
draw.background()
    .rgba(1.0, 1.0, 1.0, 0.5);
```

or 
```rust
frame.clear(Alpha { color: WHITE, alpha: 0.5 });
```

seem to work, and this kind of behaviour is not present on any example, `blend_color` seem to work just on the draw of each frame, not on previous ones.

Proposed solution (also making `.rgba` work oviously):
```rust
draw.background()
    .color(WHITE) /* Since this only accept Rgb<_, _> */
    .alpha(0.5);
```

**Comment by danwilhelm** [comment]
This is as designed! The word "clear" in the docs attempts to convey that each pixel value will be completely replaced by the rgba value passed. The alpha value actually is stored, but it doesn't have a visible effect since what was there before is replaced/"cleared". Moreover, this is accomplished in an extremely efficient way using `LOADOP_CLEAR`, which doesn't support alpha blending. (Behind the scenes, `draw.background()` actually calls `frame.clear()`.)

The desired behavior could be implemented by drawing an alpha-blended rect over the screen, which would likely be a more flexible approach than modifying `draw.background()`.

**Comment by cdecompilador** [comment]
yeah the solution I did was a `draw.rect()`, I had a hard time searching for a solution to this, maybe adding in the documentation these details would be good.

Thanks for anwering <3
