### ISSUE TITLE
Is nannou still maintained?

### ISSUE THREAD

**Issue by wjagodfrey** [nannou-org/nannou#886]
We're considering a new GUI toolkit and `nannou` looks interesting, but before getting too deep into this I'd like to know if the maintainers are still around? It looks like there's not been much activity here for several months.

If it's just so solid it doesn't need work that's fine. Would be good to know.

**Comment by JoshuaBatty** [comment]
Hi @wjagodfrey. Yes, nannou is still being maintained, just not at the same rate as it used to be. Both myself and @mitchmindtree have full time programming jobs now so our ability to work on nannou is limited to weekends now. That said, we have a new release coming out soon which will upgrade nannou to use wgpu 0.13. Hope that answers your question.

**Comment by Woyten** [comment]
An upgrade to the latest wgpu version would be awesome! Besides that, I think that Nannou's next goal should be good WASM support in order to be able to compete with similar toolkits. Good WASM support is probably just a matter of  a few tweaks here and there. I can help driving this topic forward but I prefer to wait until the latest wgpu version has been adopted.

**Comment by wjagodfrey** [comment]
@Woyten good enough for me. Thanks!

**Comment by wjagodfrey** [comment]
@JoshuaBatty good enough for me. Thanks!
